// <auto-generated />
namespace Quacka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class basicdatastructurequacks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basicdatastructurequacks));
        
        string IMigrationMetadata.Id
        {
            get { return "201505062328176_basic-data-structure-quacks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
