// <auto-generated />
namespace Quacka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class applicationuserid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applicationuserid));
        
        string IMigrationMetadata.Id
        {
            get { return "201505070410539_application-user-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
